# Generated by Django 5.0.6 on 2024-05-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مقاله')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده در')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
